import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync,writeFileSync,mkdirSync,readdirSync,statSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {execFileSync} from 'node:child_process';
import {HostedQaBases,prepareQaCheckout} from '../src/hosted-qa-base.js';

const old='a'.repeat(40),next='b'.repeat(40),later='c'.repeat(40);
const validation={repository:'test/product',base:old,checkout:'/operator/repo',image:'sha256:'+'d'.repeat(64),dependencyPath:'/seed/0',cwd:'.',gates:[{name:'test',argv:['npm','test']}]};
const profiles={agent:{branch:'main',validation}};
test('new jobs use current main; duplicates and restart preserve exact job base without carrying authority',async t=>{
 const root=mkdtempSync(join(tmpdir(),'qa-bases-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 let main=next,reads=0,prepares=0;let allowed=true;
 const source={head:async()=>{reads++;return main;},prepare:async()=>{prepares++;}};
 const intake=()=>{if(!allowed)throw new Error('intake missing');};
 const service=new HostedQaBases(root,profiles,source,intake);
 const [first,duplicate]=await Promise.all([service.prepare('agent','job1'),service.prepare('agent','job1')]);
 assert.equal(first.base,next);assert.equal(duplicate.base,next);assert.equal(reads,1);assert.equal(prepares,1);
 first.gates[0].argv.push('mutated');assert.deepEqual(duplicate.gates[0].argv,['npm','test']);
 main=later;
 const restored=new HostedQaBases(root,profiles,source,intake);
 assert.equal((await restored.prepare('agent','job1')).base,next);assert.equal(reads,1);
 assert.equal((await restored.prepare('agent','job2')).base,later);assert.equal(reads,2);
 const candidate={repository:validation.repository,base:next,changes:{'a.js':'fixed'}};
 assert.equal(restored.requireProfile('agent','job1',candidate).base,next);
 assert.throws(()=>restored.requireProfile('agent','job2',candidate),/binding/);
 assert.throws(()=>restored.requireProfile('other','job1',candidate),/Unknown/);
 allowed=false;assert.throws(()=>restored.prepare('agent','job1'),/intake/);
 for(const file of readdirSync(root))assert.equal(statSync(join(root,file)).mode&0o077,0);
});
test('dependency preparation errors retry, but changed policy never rebinds an existing job',async t=>{
 const root=mkdtempSync(join(tmpdir(),'qa-base-retry-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 let fail=true;
 const source={head:async()=>next,prepare:async()=>{if(fail)throw new Error('Dependency image refresh required');}};
 const service=new HostedQaBases(root,profiles,source,()=>{});
 await assert.rejects(service.prepare('agent','job'),/Dependency/);assert.equal(readdirSync(root).length,0);
 fail=false;assert.equal((await service.prepare('agent','job')).base,next);
 const changed=new HostedQaBases(root,{agent:{...profiles.agent,validation:{...validation,image:'sha256:'+'e'.repeat(64)}}},source,()=>{});
 assert.throws(()=>changed.prepare('agent','job'),/policy changed/);
 assert.equal((await changed.prepare('agent','new-job')).base,next);
});
test('revoked intake during preparation and malformed remote SHA do not create records',async t=>{
 const root=mkdtempSync(join(tmpdir(),'qa-base-revoke-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 let allowed=true;
 const service=new HostedQaBases(root,profiles,{head:async()=>next,prepare:async()=>{allowed=false;}},()=>{if(!allowed)throw new Error('revoked');});
 await assert.rejects(service.prepare('agent','job'),/revoked/);assert.equal(readdirSync(root).length,0);
 const invalid=new HostedQaBases(root,profiles,{head:async()=> 'main',prepare:async()=>assert.fail('must not fetch')},()=>{});
 await assert.rejects(invalid.prepare('agent','bad'),/Invalid remote/);
});
test('real Git preparation imports a new commit without changing checkout and rejects changed image inputs',async t=>{
 const root=mkdtempSync(join(tmpdir(),'qa-base-git-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const upstream=join(root,'upstream'),checkout=join(root,'checkout');mkdirSync(upstream);
 const git=(cwd:string,...args:string[])=>execFileSync('git',['-C',cwd,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 git(upstream,'init');git(upstream,'config','user.email','test@example.test');git(upstream,'config','user.name','Test');
 writeFileSync(join(upstream,'package.json'),'{}');writeFileSync(join(upstream,'app.js'),'old');
 git(upstream,'add','.');git(upstream,'commit','-m','base');const base=git(upstream,'rev-parse','HEAD');
 execFileSync('git',['clone',upstream,checkout],{stdio:'ignore'});
 // Test-only URL rewrite routes the exact GitHub URL to this local fixture. No remote credentials/network.
 git(checkout,'config',`url.${upstream}.insteadOf`,'https://github.com/test/product.git');
 writeFileSync(join(upstream,'app.js'),'new');git(upstream,'commit','-am','code');const code=git(upstream,'rev-parse','HEAD');
 const profile={...validation,base,checkout};
 await prepareQaCheckout(profile,code);
 assert.equal(git(checkout,'rev-parse','HEAD'),base);assert.equal(git(checkout,'show',`${code}:app.js`),'new');
 writeFileSync(join(upstream,'.npmrc'),'legacy-peer-deps=true');git(upstream,'add','.');git(upstream,'commit','-m','install config');
 await assert.rejects(prepareQaCheckout(profile,git(upstream,'rev-parse','HEAD')),/Dependency image refresh/);
 assert.equal(git(checkout,'rev-parse','HEAD'),base);
});

test('gateway base capability and validation receipts are bound to the prepared job',async t=>{
 const {HostedAgentGateway}=await import('../src/hosted-agent-gateway.js');
 const {hostedAgentSpecInput}=await import('../src/hosted-agent-types.js');
 const {createHostedAgentCtx}=await import('../src/hosted-agent-runtime/hostedAgentContext.js');
 const {HostedQaValidationService}=await import('../src/hosted-qa-validation-service.js');
 const {qaCandidateDigest}=await import('../src/hosted-qa-validator.js');
 const root=mkdtempSync(join(tmpdir(),'qa-base-gateway-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 const bases=new HostedQaBases(join(root,'bases'),profiles,{head:async()=>next,prepare:async()=>{}},(_id,job)=>{if(job!=='verified')throw new Error('no intake');});
 const service=new HostedQaValidationService(join(root,'results'),{agent:validation},async(p,c)=>({repository:p.repository,base:p.base,candidateDigest:qaCandidateDigest(c),passed:true,gates:[{gate:'test',passed:true,summary:'ok',diagnostics:''}]}),(id,job,c)=>{if(!job)throw new Error('job required');return bases.requireProfile(id,job,c);});
 const spec=(id:string)=>({...hostedAgentSpecInput.parse({id,name:id,model:'unused',mode:'handler',files:{'index.mjs':'export default {}'}}),version:1,owner:'test',createdAt:1,updatedAt:1});
 const gateway=new HostedAgentGateway({registry:()=>null,spec:id=>spec(id),log:()=>{},qaBase:(id,job)=>bases.submit(id,job),qaValidation:(id,input)=>service.submit(id,input)});
 const url=await gateway.listen('127.0.0.1');t.after(()=>gateway.close());
 const token=gateway.issue('agent'),ctx=createHostedAgentCtx({spec:spec('agent'),gateway:{url,token},secrets:{},log:()=>{}},{text:''});
 await assert.rejects(ctx.qa!.base!('unverified'),/refused/);
 assert.equal((await ctx.qa!.base!('verified') as any).state,'running');await bases.drain();
 assert.deepEqual(await ctx.qa!.base!('verified'),{state:'done',result:{repository:validation.repository,base:next}});
 const c={repository:validation.repository,base:next,changes:{'code.js':'fixed'}};
 await assert.rejects(ctx.qa!.validate(c),/refused/);
 await assert.rejects(ctx.qa!.validate(c,'unverified'),/refused/);
 await assert.rejects(ctx.qa!.validate({...c,base:later},'verified'),/refused/);
 assert.equal((await ctx.qa!.validate(c,'verified') as any).state,'running');await new Promise(r=>setImmediate(r));
 assert.equal(service.requirePassed('agent',c,'verified').passed,true);
 assert.throws(()=>service.requirePassed('agent',c),/job required/);
 assert.throws(()=>service.requirePassed('agent',c,'unverified'),/no intake/);
 gateway.revoke(token);await assert.rejects(ctx.qa!.base!('verified'),/refused/);
});

test('host-authorized revalidation advances a durable attempt once and rejects old candidates', async t => {
 const root=mkdtempSync(join(tmpdir(),'qa-base-next-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 let main=old,prepares=0,authorized=true;
 const source={head:async()=>main,prepare:async()=>{prepares++;}};
 const authority=()=>{if(!authorized)throw new Error('review invalidation missing');};
 const service=new HostedQaBases(root,profiles,source,()=>{},authority);
 await service.prepare('agent','job');main=next;
 const request={previousBase:old,sequence:1,sourceDigest:'e'.repeat(64)};
 const [first,duplicate]=await Promise.all([service.prepareRevalidation('agent','job',request),service.prepareRevalidation('agent','job',request)]);
 assert.deepEqual(first,{jobId:'job',repository:validation.repository,...request,base:next});assert.deepEqual(first,duplicate);
 assert.equal(prepares,2);first.base=later;assert.equal(duplicate.base,next);
 const restored=new HostedQaBases(root,profiles,source,()=>{},authority);main=later;
 assert.deepEqual(await restored.prepareRevalidation('agent','job',request),duplicate);assert.equal(prepares,2);
 assert.equal((await restored.prepare('agent','job')).base,next);
 assert.throws(()=>restored.requireProfile('agent','job',{repository:validation.repository,base:old,changes:{'a.js':'old'}}),/binding/);
 assert.equal(restored.requireProfile('agent','job',{repository:validation.repository,base:next,changes:{'a.js':'new'}}).base,next);
 assert.throws(()=>restored.prepareRevalidation('agent','job',{...request,sourceDigest:'f'.repeat(64)}),/attempt changed/);
 authorized=false;assert.throws(()=>restored.prepareRevalidation('agent','job',request),/invalidation/);
 authorized=true;
 const second=await restored.prepareRevalidation('agent','job',{previousBase:next,sequence:2,sourceDigest:'f'.repeat(64)});
 assert.equal(second.base,later);assert.equal(second.sequence,2);
 assert.throws(()=>restored.prepareRevalidation('agent','job',request),/attempt changed/);
 const record=JSON.parse(readFileSync(join(root,readdirSync(root)[0]),'utf8'));
 assert.deepEqual(record.attempts.map(attempt=>[attempt.previousBase,attempt.base]),[[old,next],[next,later]]);
});

test('revalidation checks authority after preparation and cannot overwrite the base on failure', async t => {
 const root=mkdtempSync(join(tmpdir(),'qa-base-next-deny-'));t.after(()=>rmSync(root,{recursive:true,force:true}));
 let main=old,allowed=true,release:()=>void=()=>{},started:()=>void=()=>{};
 const began=new Promise<void>(resolve=>{started=resolve;});
 const source={head:async()=>main,prepare:async()=>{if(main!==old){started();await new Promise<void>(resolve=>{release=resolve;});}}};
 const service=new HostedQaBases(root,profiles,source,()=>{},()=>{if(!allowed)throw new Error('release now pending');});
 await service.prepare('agent','job');
 const request={previousBase:old,sequence:1,sourceDigest:'e'.repeat(64)};
 assert.throws(()=>new HostedQaBases(root,profiles,source,()=>{}).prepareRevalidation('agent','job',request),/authority unavailable/);
 assert.throws(()=>new HostedQaBases(root,profiles,source,()=>{},async()=>{throw new Error('denied');}).prepareRevalidation('agent','job',request),/must be synchronous/);
 await assert.rejects(service.prepareRevalidation('agent','job',request),/No new remote base/);
 main=next;
 const pending=service.prepareRevalidation('agent','job',request);await began;
 assert.throws(()=>service.prepareRevalidation('agent','job',{...request,sourceDigest:'f'.repeat(64)}),/already running/);
 allowed=false;release();await assert.rejects(pending,/release now pending/);
 assert.equal((await service.prepare('agent','job')).base,old);
 const record=JSON.parse(readFileSync(join(root,readdirSync(root)[0]),'utf8'));assert.equal(record.attempts,undefined);
});
