/** Repository routes use the same agent visibility and source ownership as the existing API. */
export function agentRepositoryPaths() {
  const string = { type: 'string' };
  const sha = { type: 'string', pattern: '^[a-f0-9]{40,64}$' };
  const body = (properties: Record<string, unknown>, required: string[] = []) => ({ required: true, content: { 'application/json': { schema: { type: 'object', properties, required } } } });
  const params = (path: string) => [...path.matchAll(/\{(\w+)\}/g)].map((match) => ({ name: match[1], in: 'path', required: true, schema: ['number', 'comment'].includes(match[1]!) ? { type: 'integer', minimum: 1 } : string }));
  const query = (name: string, schema: unknown = string, required = false) => ({ name, in: 'query', required, schema });
  const paths: Record<string, Record<string, unknown>> = {};
  const add = (path: string, method: string, summary: string, description: string, extra: Record<string, unknown> = {}) => {
    paths[path] ??= {};
    paths[path]![method] = { tags: ['Agents'], summary, description, security: [], parameters: params(path), responses: {
      200: { description: 'Result; read responses use application/json unless described otherwise' },
      400: { description: 'Invalid request or ref' }, 401: { description: 'Authentication required' },
      403: { description: 'Operation not permitted' }, 404: { description: 'Unknown or unreadable resource' },
      409: { description: 'Read-only source, conflict or runtime not ready' },
    }, ...extra };
  };
  const agent = '/api/hosted-agents/{id}';
  const acl = 'Visibility is the same as reading the agent. Owner/organization writers may push and merge. A project-bound or mirrored source refuses local writes with read_only_source; edit and push its original repository instead.';
  add('/git/{id}.git/info/refs', 'get', 'Discover Git refs (smart HTTP)', `${acl} Git clients use HTTP Basic with an ainize API key as the password. Workspace sessions and bearer credentials also work.`, { parameters: [...params('/git/{id}.git/info/refs'), query('service', { type: 'string', enum: ['git-upload-pack', 'git-receive-pack'] }, true)], responses: { 200: { description: 'Git service advertisement; application/x-git-*-advertisement' }, 401: { description: 'Git credential challenge' }, 404: { description: 'Unknown or unreadable repository' } } });
  for (const service of ['upload-pack', 'receive-pack']) add(`/git/{id}.git/git-${service}`, 'post', service === 'upload-pack' ? 'Clone or fetch an agent repository' : 'Push an agent repository and apply main', `${acl} Packs are binary. A rejected pre-receive validation leaves refs unchanged. Main application finishes before receive-pack responds. Proposal branches do not deploy.`, { requestBody: { required: true, content: { [`application/x-git-${service}-request`]: { schema: { type: 'string', format: 'binary' } } } }, responses: { 200: { description: `application/x-git-${service}-result (Git protocol reports accepted/rejected refs)` }, 401: { description: 'Git credential challenge' }, 404: { description: 'Unknown or unreadable repository' } } });
  add(`${agent}/executions`, 'get', 'Read persisted runtime execution history', acl + ' Newest first; previous successful and failed executions survive restart. Private/no-store.', { parameters: [...params(agent), query('limit', { type: 'integer', minimum: 1, maximum: 200, default: 50 }), query('offset', { type: 'integer', minimum: 0, default: 0 })] });
  add(`${agent}/commits`, 'get', 'Read commit history', acl, { parameters: [...params(agent), query('ref'), query('limit', { type: 'integer', minimum: 1, maximum: 200, default: 50 })] });
  add(`${agent}/refs`, 'get', 'Read branches and clone URL', acl);
  add(`${agent}/tree`, 'get', 'Read a file or paths at a ref', acl, { parameters: [...params(agent), query('ref'), query('path')] });
  add(`${agent}/diff`, 'get', 'Review a proposal diff', 'Three-dot diff from base to head. Cross-repository proposals expose their imported, pinned headCommit in the original repository.', { parameters: [...params(agent), query('base'), query('head')] });
  add(`${agent}/forks`, 'post', 'Create a private source fork', 'Any authenticated reader may fork. The resulting fork is owner-only and creates no runtime or secrets. Ten forks per owner, one thousand total.', { requestBody: body({ ref: { type: 'string', default: 'main' } }), responses: { 201: { description: '{ fork, clonePath }' }, 400: { description: 'Invalid source or fork quota reached' }, 401: { description: 'Sign in' }, 404: { description: 'No readable repository' } } });
  add('/api/agent-forks', 'get', 'List your private repository forks', 'Authenticated owner only.');
  add('/api/agent-forks/{id}', 'delete', 'Delete your private source fork', 'Owner only; an imported proposal SHA remains available for review and merge.');
  add(`${agent}/pulls`, 'get', 'List repository proposals', acl, { parameters: [...params(agent), query('state', { type: 'string', enum: ['open', 'merged', 'closed'] })] });
  add(`${agent}/pulls`, 'post', 'Open a branch or cross-repository proposal', 'An authenticated reader may propose an existing branch or their private fork via headAgent. Fork ownership and parent must match. The imported cross-repository head SHA is pinned when the proposal opens.', { requestBody: body({ head: string, headAgent: string, base: { type: 'string', default: 'main' }, title: { type: 'string', minLength: 1, maxLength: 120 }, body: { type: 'string', maxLength: 4000 } }, ['head', 'title']), responses: { 201: { description: '{ pull }' }, 400: { description: 'Invalid branch or proposal' }, 401: { description: 'Sign in' }, 403: { description: 'Not your fork of this repository' }, 409: { description: 'Source is read-only' } } });
  add(`${agent}/pulls/{number}`, 'get', 'Read a proposal', acl);
  add(`${agent}/pulls/{number}/merge`, 'post', 'Validate and merge a proposal', `${acl} Validates the merged result before refs move. Conflicts and invalid resulting specs are refused. Cross-repository merges use the reviewed SHA even after the fork changes or is deleted.`);
  add(`${agent}/pulls/{number}/close`, 'post', 'Close a proposal', 'Proposal author or someone who may merge only.');
  add(`${agent}/pulls/{number}/comments`, 'get', 'Read proposal review comments', 'Same proposal visibility. Deleted comments retain author, anchor and deletion timestamp but their body is removed.');
  add(`${agent}/pulls/{number}/comments`, 'post', 'Add a general or source-anchored review comment', 'Authenticated proposal reader. An anchor requires an existing full commit SHA, path and line; comments are stored durably.', { requestBody: body({ body: { type: 'string', minLength: 1, maxLength: 8000 }, commit: sha, path: string, line: { type: 'integer', minimum: 1 } }, ['body']) });
  add(`${agent}/pulls/{number}/comments/{comment}`, 'patch', 'Edit your review comment', 'Comment author only.', { requestBody: body({ body: { type: 'string', minLength: 1, maxLength: 8000 } }, ['body']) });
  add(`${agent}/pulls/{number}/comments/{comment}`, 'delete', 'Remove a review comment', 'Author or someone who may merge; retains a tombstone.');
  add(`${agent}/mirror`, 'get', 'Read GitHub mirror state', 'Same agent visibility; includes last sync commit and error.');
  add(`${agent}/mirror`, 'put', 'Attach an agent to a GitHub source', `${acl} Fetches once, then periodically reconciles. Repository path selects the agent folder.`, { requestBody: body({ url: string, branch: { type: 'string', default: 'main' }, path: { type: 'string', default: '' } }, ['url']) });
  add(`${agent}/mirror/sync`, 'post', 'Reconcile a GitHub mirror now', 'Writers only; sync shares the same serialized pipeline as automatic reconciliation.');
  add(`${agent}/mirror`, 'delete', 'Detach a GitHub mirror', 'Writers only. Stops following without reverting the current agent.');
  add('/api/agent-mirrors/webhook', 'post', 'Reconcile mirrors after a signed GitHub push', 'AINIZE_AGENT_MIRROR_WEBHOOK_SECRET must be configured. X-Hub-Signature-256 is HMAC-SHA256 over the original request bytes. Only matching source/branch mirrors sync; the periodic timer recovers missed events.', { parameters: [{ name: 'X-Hub-Signature-256', in: 'header', required: true, schema: string }], responses: { 200: { description: '{ synced }' }, 401: { description: 'Invalid signature' }, 404: { description: 'Webhook secret not configured' } } });
  add(`${agent}/preview-runs`, 'get', 'Read your persisted proposal conversations', 'Authenticated reader and record owner only. Fixed source commit, model, request and bounded response survive preview expiry. Private/no-store.');
  add(`${agent}/previews`, 'post', 'Start an isolated proposal runtime at a fixed SHA', 'Authenticated repository readers. The preview is owner-only, expires after fifteen minutes, inherits no production secrets/allowlist/media permissions, and never updates the source runtime. Two per person, eight total.', { requestBody: body({ ref: string }, ['ref']), responses: { 202: { description: '{ preview: { id, agent, commit, owner, createdAt, expiresAt, status, error } }' }, 401: { description: 'Sign in' }, 404: { description: 'No readable repository' }, 409: { description: 'Invalid source or preview quota/build failure' } } });
  add('/api/agent-previews/{preview}', 'get', 'Read your temporary proposal runtime', 'Owner must still be able to read the source. Private/no-store; expired previews return 404.');
  add('/api/agent-previews/{preview}', 'delete', 'Stop your temporary proposal runtime', 'Owner only. Aborts active requests, revokes gateway authority and removes the temporary runtime and images.');
  add('/api/agent-previews/{preview}/rpc', 'post', 'Talk to your proposal before merging', 'Owner/source-reader only, ready preview required. A2A JSON-RPC message/send, message/stream, tasks/get and tasks/cancel; maximum 64 KiB. JSON or SSE response. Expiry and client cancellation abort the upstream request.', { requestBody: body({ jsonrpc: { type: 'string', const: '2.0' }, id: {}, method: { type: 'string', enum: ['message/send', 'message/stream', 'tasks/get', 'tasks/cancel'] }, params: { type: 'object' } }, ['method']) });
  add('/api/projects/{id}/source', 'get', 'Read the manifest from an immutable execution source', 'Same project viewer/actor permission as Run. Deployed means last successful active deployment; a newer failure does not replace it. Returns {repoId,target,sha,sourcePath,manifest}, private/no-store. Use the returned SHA with target=commit to keep form and execution together.', { tags: ['Projects'], parameters: [...params('/api/projects/{id}'), query('target', { type: 'string', enum: ['head', 'commit', 'deployed'], default: 'head' }), query('sha', sha)] });
  return paths;
}
